IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Exams' AND TABLE_SCHEMA = 'dbo')
    drop table dbo.Exams;

CREATE TABLE Exams
(
    [Id] Int NOT NULL PRIMARY KEY IDENTITY(1,1),
    [Counter] Int NOT NULL DEFAULT 0
)